### ISSUE TITLE
Add hook to direct download version of telegram (org.telegram.messenger.web)

### ISSUE THREAD

**Issue by Chilace** [shatyuka/Killergram#1]
![2021-11-09 23-37-46 Telegram for Android - Google Chrome](https://user-images.githubusercontent.com/22879802/141004499-534c1882-50cc-4863-99d8-aff6b2c87901.png)

**Comment by shatyuka** [comment]
I'll have a look.

**Comment by shatyuka** [comment]
Commit 05f2bf3.
