### ISSUE TITLE
invalid for the latest nekogram x

### ISSUE THREAD

**Issue by asdqp233** [shatyuka/Killergram#14]
For this version of the Nekogram X (v8.4.2-preview01 arm64-v8a full release
AndroidLibV2rayLite v23, V2fly-core v4.37.2）
it cannot prevent it from displaying the sponsored ads
![Screenshot_20220102-011113_Nekogram X](https://user-images.githubusercontent.com/52170460/147856079-8b36e37c-bc1a-4c4f-b530-96caecbac333.png)

**Comment by asky88** [comment]
遇到了同样的情况，作者有空修复一下

**Comment by Henvy-Mango** [comment]
遇到同样的问题

For this version

> Nekogram X v8.4.2-preview01 arm64-v8a full releaseNoGcm AndroidLibV2rayLite v23, V2fly-core v4.37.2

**Comment by shatyuka** [comment]
Fixed in commit 74ab6ae.
