### ISSUE TITLE
请求支持Graph Messenger

### ISSUE THREAD

**Issue by xushet** [shatyuka/Killergram#15]
https://play.google.com/store/apps/details?id=ir.ilmili.telegraph
![Screenshot_20220103-124507_Shady启动器.png](https://user-images.githubusercontent.com/34502902/147900268-705f4ac9-3615-435f-9be0-42184843de1e.png)

我是指频道底部的加密货币广告
![Screenshot_20220103-124436_Telegraph.png](https://user-images.githubusercontent.com/34502902/147900248-431babe5-b86c-46f7-ad11-707e52d06871.png)

先谢谢大佬了

**Comment by xushet** [comment]
关于应用内的谷歌广告，同样在用Graph Messenger的朋友，你可以去谷歌找去国外大佬改的广告版或者用mat禁用广告活动

**Comment by shatyuka** [comment]
DO NOT SPAM

**Comment by xqhjay** [comment]
> 关于应用内的谷歌广告，同样在用Graph Messenger的朋友，你可以去谷歌找去国外大佬改的广告版或者用mat禁用广告活动

你说的是哪个修改版本？mat是啥？
