### ISSUE TITLE
don't work with tw.nekomimi.nekogram

### ISSUE THREAD

**Issue by Sergo1217** [shatyuka/Killergram#17]
![Screenshot_2022-01-17-19-48-33-086_com android shell](https://user-images.githubusercontent.com/16447886/149809401-cb26fd81-4704-4c64-8859-0dad38ceebf8.jpg)

**Comment by shatyuka** [comment]
Nekogram provides this function itself.
Related pull request: https://github.com/shatyuka/Killergram/pull/9

**Comment by Sergo1217** [comment]
> Nekogram provides this function itself. Related pull request: #9

it's not true. Nekogram don't have this features

**Comment by shatyuka** [comment]
It should have. Find it yourself.

**Comment by Sergo1217** [comment]
> It should have. Find it yourself.

Telegram don't allow third-party clients to remove ads

**Comment by LittleChest** [comment]
> Nekogram 本身就提供了这个功能。 相关拉取请求：#9

No, it doesn't provide this functionality. And its developers did not say why Nekogram was removed.

Its developers should not interfere with third-party Xposed.

**Comment by cracky5322** [comment]
> 

Just because you can't find it or you don't know it doesn't mean it doesn't have this function, please find the method provided by Nekogram by yourself

And the lawmaker has the right to restrict Xposed Hook, please don't emotional blackmail

**Comment by OrStudio** [comment]
> > Nekogram 本身就提供了这个功能。 相关拉取请求：#9
> 
> No, it doesn't provide this functionality. And its developers did not say why Nekogram was removed.
> 
> Its developers should not interfere with third-party Xposed.

Just because you can't find it or you don't know it doesn't mean it doesn't have this function, please find the method provided by Nekogram by yourself

And the lawmaker has the right to restrict Xposed Hook, please don't emotional blackmail

**Comment by LittleChest** [comment]
> > > Nekogram 本身就提供了这个功能。 相关拉取请求：#9
> > 
> > 
> > No, it doesn't provide this functionality. And its developers did not say why Nekogram was removed.
> > Its developers should not interfere with third-party Xposed.
> 
> Just because you can't find it or you don't know it doesn't mean it doesn't have this function, please find the method provided by Nekogram by yourself

Please let me know if you know where it is.

> And the lawmaker has the right to restrict Xposed Hook, please don't emotional blackmail

OK, I get it.

**Comment by OrStudio** [comment]
> > > > Nekogram 本身就提供了这个功能。 相关拉取请求：#9
> > > 
> > > 
> > > No, it doesn't provide this functionality. And its developers did not say why Nekogram was removed.
> > > Its developers should not interfere with third-party Xposed.
> > 
> > 
> > Just because you can't find it or you don't know it doesn't mean it doesn't have this function, please find the method provided by Nekogram by yourself
> 
> Please let me know if you know where it is.
> 
> > And the lawmaker has the right to restrict Xposed Hook, please don't emotional blackmail
> 
> OK, I get it.

If the developer is not willing to disclose the usage method, then the user can only find it by themselves, and I will not disclose any hidden functions of the developer.

**This topic ends here**
