### ISSUE TITLE
Реклама показывается.

### ISSUE THREAD

**Issue by advokat11** [shatyuka/Killergram#21]
Forkgram 8.4.4.0
![Screenshot_20220129-133826.jpg](https://user-images.githubusercontent.com/59486045/151657839-815e7df1-90be-482e-87b3-f7998fe75ea6.jpg)

![Screenshot_20220129-133921.jpg](https://user-images.githubusercontent.com/59486045/151657840-79951c07-601c-44f5-af18-0403a2149af6.jpg)

**Comment by advokat11** [comment]
![Screenshot_20220130-233221.jpg](https://user-images.githubusercontent.com/59486045/151716714-7940e30b-00c5-495e-8b02-04c7e801fa38.jpg)

**Comment by shatyuka** [comment]
Commit 472f373
