### ISSUE TITLE
Improvement: disable proximity sensor in voice play

### ISSUE THREAD

**Issue by modma** [shatyuka/Killergram#22]
A very bad trick of telegram is the buggy proximity sensor activation how a audio message is played...
Can you disable the use of the sensor in this stages? Is a headache a long play, low volume and the screens turns off...

**Comment by shatyuka** [comment]
Report this to Telegram development team.

**Comment by KelvinCrag** [comment]
> A very bad trick of telegram is the buggy proximity sensor activation how a audio message is played... Can you disable the use of the sensor in this stages? Is a headache a long play, low volume and the screens turns off...

You can disable the sensor feature at telegram settings>chat settings: "raise to speak"

![Screenshot_20220311-225025~3](https://user-images.githubusercontent.com/64832927/157975723-06ae3786-b658-4f0d-b458-8048c4acf4e5.png)
