### ISSUE TITLE
Add some more hooks

### ISSUE THREAD

**Issue by mitrillov** [shatyuka/Killergram#4]
Hello! Thank you for this amazing project. There are some more popular Telegram clients that you have not supported yet. Please, add hooks for this apps:

org.telegram.messenger.beta
org.telegram.BifToGram 
ir.ilmili.telegraph 
ir.ilmili.telegraph.second
ir.ilmili.telegraph.third
com.iMe.android 
org.vidogram.messenger

**Comment by shatyuka** [comment]
Graph Messenger and Vidogram use proguard, so we can not simply use class name to hook the method.
And I'm tired to look into all of the unofficial apps.

**Comment by shatyuka** [comment]
- [x] org.telegram.messenger.beta
- [x] org.telegram.BifToGram
- [ ] ir.ilmili.telegraph
- [ ] ir.ilmili.telegraph.second
- [ ] ir.ilmili.telegraph.third
- [x] com.iMe.android
- [ ] org.vidogram.messenger

**Comment by shatyuka** [comment]
Confirmed that Vidogram has removed sponsored messages. Not sure about Graph Messenger.

**Comment by mitrillov** [comment]
Thank you for your work and research!
